import numpy as np 
def graspInput(configs,zz=0,mct=1,av=False):
    gg = open('GRASP.INP','w')
    jjlsj = 3 
    if av:
        jjlsj = 0
    numcfgs = len(configs[:,0])
    gg.write('GRASP: Ge Isolelectronic Sequence\n')
    gg.write(f' {numcfgs} 9  {jjlsj}  ! CSFs,orbitals,IOP,ATW\n')
    gg.write(' 1S  2     \n')
    gg.write(' 2S  2     \n')
    gg.write(' 2P  6     \n')
    gg.write(' 3S  2     \n')
    gg.write(' 3P  6     \n')
    gg.write(' 3D 10     \n')
    gg.write(' 4S  '  + (numcfgs*'{} ').format(*configs[:,0])   +' \n')
    gg.write(' 4P  '  + (numcfgs*'{} ').format(*configs[:,1])   +' \n')
    gg.write(' 5S  '  + (numcfgs*'{} ').format(*configs[:,2])   +' \n')
    gg.write('ANG  7 13 \n')
    gg.write('-1                !all poss Jp\n')
    gg.write('MCP\n')
    gg.write('MCBP\n')
    gg.write('MCT  {}  0         !E1 only\n'.format(mct))
    gg.write('MCDF \n')
    gg.write('0 0 0             !write new MCDF.DAT\n')
    gg.write('{}\n'.format(zz))
    gg.write('FIX 0\n')
    gg.write('EAL 35\n')
    gg.write('BENA 20\n')
    gg.write('\n')
    if (av):
        try:
            shift = np.loadtxt('shift')
            shiftExist = True 
        except:
            shiftExist = False 
            
        if shiftExist:
            gg.write('OSCL 17 9 10 11 \n')
            gg.write('1:{}\n'.format(len(shift)))
            for ii,ss in enumerate(shift):
                if ii < len(shift)-1:
                    gg.write('{}c\n'.format(ss))
                else:
                    gg.write('{}\n'.format(ss))
                
        else:
            gg.write('OSCL 9 10 11 \n')
            gg.write('\n')
    else:
        gg.write('OSCL 20 9 10 11 \n')
        gg.write('\n')        
    gg.write('STOP\n')
    gg.close()
    return 0 


def run0():    
    gg = open('GRASP.INP','w')
    gg.write('GRASP: Ge Isolelectronic Sequence\n')
    gg.write('4 9  3  ! CSFs,orbitals,IOP,ATW\n')
    gg.write(' 1S  2     \n')
    gg.write(' 2S  2     \n')
    gg.write(' 2P  6     \n')
    gg.write(' 3S  2     \n')
    gg.write(' 3P  6     \n')
    gg.write(' 3D  10 10 10 10 !! 8 10 10 10  8 7 6\n')
    gg.write(' 4S   2  1  0  2 !! 2  2  0  1  0 0 0\n' )
    gg.write(' 4P   2  3  4  1 !! 2  0  0  0  0 0 0\n' ) 
    gg.write(' 4D   0  0  0  1 !! 2  2  4  3  6 7 8\n')
    gg.write('ANG  7 13 \n')
    gg.write('-1                !all poss Jp\n')
    gg.write('MCP\n')
    gg.write('MCBP\n')
    gg.write('MCT  1  0         !E1 only\n')
    gg.write('MCDF \n')
    gg.write('0 0 0             !write new MCDF.DAT\n')
    gg.write('{}\n'.format(zz))
    gg.write('FIX 0\n')
    gg.write('EAL 35\n')
    gg.write('BENA 20\n')
    gg.write('\n')
    gg.write('OSCL 20 9 10 11 \n')
    gg.write('\n')
    gg.write('STOP\n')
    gg.close()

def run1():    
    gg = open('GRASP.INP','w')
    gg.write('GRASP: Ge Isolelectronic Sequence\n')
    gg.write('11 9  0  ! CSFs,orbitals,IOP,ATW\n')
    gg.write(' 1S  2     \n')
    gg.write(' 2S  2     \n')
    gg.write(' 2P  6     \n')
    gg.write(' 3S  2     \n')
    gg.write(' 3P  6     \n')
    gg.write(' 3D  10 10 10 10 10 10 8  10  8 7 6\n')
    gg.write(' 4S   2  1  0  2  2  0 2   1  0 0 0\n' )
    gg.write(' 4P   2  3  4  1  0  0 2   0  0 0 0\n' ) 
    gg.write(' 4D   0  0  0  1  2  4 2   3  6 7 8\n')
    gg.write('ANG  7 13 \n')
    gg.write('-1                !all poss Jp\n')
    gg.write('MCP\n')
    gg.write('MCBP\n')
    gg.write('MCT  1  0         !E1 only\n')
    gg.write('MCDF \n')
    gg.write('0 0 0             !write new MCDF.DAT\n')
    gg.write('{}\n'.format(zz))
    gg.write('FIX 1:12\n')
    gg.write('EAL 35\n')
    gg.write('BENA 20\n')
    gg.write('\n')
    gg.write('OSCL 20 9 10 11 \n')
    gg.write('\n')
    gg.write('STOP\n')
    gg.close()

def run1_works():    
    gg = open('GRASP.INP','w')
    gg.write('GRASP: Ge Isolelectronic Sequence\n')
    gg.write('11 9  0  ! CSFs,orbitals,IOP,ATW\n')
    gg.write(' 1S  2     \n')
    gg.write(' 2S  2     \n')
    gg.write(' 2P  6     \n')
    gg.write(' 3S  2     \n')
    gg.write(' 3P  6     \n')
    gg.write(' 3D  10 10 10 10 8 10 10 10  8 7 6\n')
    gg.write(' 4S   2  1  0  2 2  2  0  1  0 0 0\n' )
    gg.write(' 4P   2  3  4  1 2  0  0  0  0 0 0\n' ) 
    gg.write(' 4D   0  0  0  1 2  2  4  3  6 7 8\n')
    gg.write('ANG  7 13 \n')
    gg.write('-1                !all poss Jp\n')
    gg.write('MCP\n')
    gg.write('MCBP\n')
    gg.write('MCT  1  0         !E1 only\n')
    gg.write('MCDF \n')
    gg.write('0 0 0             !write new MCDF.DAT\n')
    gg.write('{}\n'.format(zz))
    gg.write('FIX 1:12\n')
    gg.write('EAL 35\n')
    gg.write('BENA 20\n')
    gg.write('\n')
    gg.write('OSCL 20 9 10 11 \n')
    gg.write('\n')
    gg.write('STOP\n')
    gg.close()    
    
def run2():    
    gg = open('GRASP.INP','w')
    gg.write('GRASP: Se Isolelectronic Sequence\n')
    gg.write('9 11  -3  ! CSFs,orbitals,IOP,ATW\n')
    gg.write(' 1S  2     \n')
    gg.write(' 2S  2     \n')
    gg.write(' 2P  6     \n')
    gg.write(' 3S  2     \n')
    gg.write(' 3P  6     \n')
    gg.write(' 3D  10 10 10 10 10 10 10 10 10 \n')
    gg.write(' 4S   2  1  0  2  2  2  0  2  2 \n' )
    gg.write(' 4P   2  3  4  1  1  1  2  0  0 \n' ) 
    gg.write(' 4D   0  0  0  1  0  0  2  2  0 \n')
    gg.write(' 5S   0  0  0  0  1  0  0  0  0 \n')
    gg.write(' 5P   0  0  0  0  0  1  0  0  2 \n')
    gg.write('ANG  7 12 \n')
    gg.write('-1                !all poss Jp\n')
    gg.write('MCP\n')
    gg.write('MCBP\n')
    gg.write('MCT  1  0         !E1 only\n')
    gg.write('MCDF \n')
    gg.write('1 0 0             !write new MCDF.DAT\n')
    gg.write('{}\n'.format(zz))
    gg.write('FIX 1:14\n')
    gg.write('EAL 35\n')
    gg.write('BENA 20\n')
    gg.write('\n')
    gg.write('OSCL 9 10 11 \n')
    gg.write('1:5\n')
    gg.write('STOP\n')
    gg.close()
